require('settings')
require('plugins')
require('plugins/nvim-compe')
require('plugins/nvim-lsp')
require('plugins/nvim-dap')
require('plugins/nvim-syntax')
require('plugins/nvim-explorer')
require('plugins/nvim-general')
require('lookandfeel')

